server:
  port: 8080

spring:
  application:
    name: eureka-consumer

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@eureka-server:777/eureka, http://root:root@eureka-server2:778/eureka
  instance:
    prefer-ip-address: true #ip的形式注册到Eureka 不设置默认是 hostname
    metadata-map:
        my-metadata: 9999999999999999999