#-------------统一配置所有的 defaultZone到公共的 profile配置里 然后每个根据不同的hostname 去匹配不同的Eureka服务器
#测试 是打包的形式 启动不通的profile配置来互相链接测试  eureka不能通过localhost来互相连接
#修改hosts文件：127.0.0.1 eureka-server eureka-server2 eureka-server3
#java -jar .\EurekaServers-1.0-SNAPSHOT.jar --spring.profiles.active=eureka-server
#java -jar .\EurekaServers-1.0-SNAPSHOT.jar --spring.profiles.active=eureka-server2
#java -jar .\EurekaServers-1.0-SNAPSHOT.jar --spring.profiles.active=eureka-server3

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@eureka-server:8671/eureka, http://admin:123@eureka-server2:8672/eureka, http://admin:123@eureka-server3:8673/eureka

#Eureka 服务器1  http://eureka-server:8671/eureka
---
server:
  port: 8671
spring:
  profiles:
    eureka-server
eureka:
  instance:
    hostname: eureka-server

#Eureka 服务器2  http://eureka-server2:8672/eureka
---
server:
  port: 8672
spring:
  profiles:
    eureka-server2
eureka:
  instance:
    hostname: eureka-server2

#Eureka 服务器3 http://eureka-server3:8673/eureka
---
server:
  port: 8673
spring:
  profiles:
    eureka-server3
eureka:
  instance:
    hostname: eureka-server3
