#-------------这种方式 是 每个server配置 defaultZone 要连接的其他的server的地址  application.yml中有另一种都写一起把所有集群地址
#测试 是打包的形式 启动不通的profile配置来互相链接测试  eureka不能通过localhost来互相连接
#修改hosts文件：127.0.0.1 eureka-server eureka-server2 eureka-server3
#java -jar .\EurekaServers-1.0-SNAPSHOT.jar
#java -jar .\EurekaServers-1.0-SNAPSHOT.jar --spring.profiles.active=eureka-server2
#java -jar .\EurekaServers-1.0-SNAPSHOT.jar --spring.profiles.active=eureka-server3

spring:
  application:
    name: eureka-server
  #默认开启第一个Server
  profiles:
    active: eureka-server


#Eureka集群 原理就是EurekaServer相互之间注册
#Eureka集群要把服务相互注册 和 从server拉取注册信息打开 不能关闭

#Eureka 8671的server
---
server:
  port: 8671
spring:
  profiles: eureka-server
eureka:
  instance:
    hostname: eureka-server
  #配置当前server要连接的server的地址
  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZome: http://eureka-server:8671/eureka
    #写的是要集群连接到的server
    service-url:
      defaultZone: http://eureka-server2:8672/eureka,http://eureka-server3:8673/eureka

#Eureka 8672的 server
---
server:
  port: 8672
spring:
  profiles: eureka-server2
eureka:
  instance:
    hostname: eureka-server2
  #配置当前server要连接的server的地址
  client:
    #写的是要集群连接到的server
    service-url:
      defaultZone: http://eureka-server:8671/eureka,http://eureka-server3:8673/eureka

#Eureka 8673 的server
---
server:
  port: 8673

spring:
  profiles: eureka-server3
eureka:
  instance:
    hostname: eureka-server3
  client:
    service-url:
      defaultZone: http://eureka-server:8671/eureka, http://eureka-server2:8672/eureka
