server:
  port: 8081

spring:
  application:
    name: provider-user

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:777/eureka
