#配置访问端口
server:
  port: 8080

#eureka客户端服务名
spring:
  application:
    name: thread-consumer

#设置Eureka客户端配置
eureka:
  client:
    fetch-registry: true #从server获取注册的服务信息
    register-with-eureka: true #注册到eureka服务器
    service-url:
      defaultZone: http://localhost:777/eureka #注册到这个地址的eureka
  instance:
    prefer-ip-address: true #把client的ip注册到eureka 默认是主机名

#配置 Ribbon 访问策略
# -- 配置全局默认的策略
ribbon:
  #配置 负载均衡 分配策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# -- 单个服务配置策略
thread-produce:
  ribbon:
    #配置 负载均衡 分配策略
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
