spring:
  profiles:
    active: server
  application:
    name: eureak-server
  security:
    user:
      name: root
      password: root

eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka-server:777/eureka, http://root:root@eureka-server2:778/eureka
---
server:
  port: 777

spring:
  profiles: server

eureka:
  instance:
    hostname: eureka-server
  client:
    fetch-registry: true #不从其他server拉取注册信息
    register-with-eureka: true #不注册到server 因为这就是个server

---
server:
  port: 778

spring:
  profiles: server2

eureka:
  instance:
    hostname: eureka-server2
  client:
    register-with-eureka: true
    fetch-registry: true

