#配置访问端口
server:
  port: 8080

#eureka客户端服务名
spring:
  application:
    name: thread-consumer

logging:
  level:
    thread.consumer: info

#设置Eureka客户端配置
eureka:
  client:
    fetch-registry: true #从server获取注册的服务信息
    register-with-eureka: true #注册到eureka服务器
    service-url:
      defaultZone: http://localhost:777/eureka #注册到这个地址的eureka
  instance:
    prefer-ip-address: true #把client的ip注册到eureka 默认是主机名

#设置FeignRest调用配置
feign:
  #开启Feign对与请求和响应的压缩
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

  client:
    config:
      #为单独的 服务配置Feign配置
      thread-produce:
        loggerLevel: BASIC #配置Feign日志 为full
        contract: feign.Contract.Default  #配置默认的FeignClient用的契约
      #配置全局的Feign配置
      default:
        loggerLevel: BASIC
    default-to-properties: true  #控制属性配置是否优先与java配置  false不优先 true优先
