server:
  port: 8671

#配置Eureka
eureka:
  client:
    register-with-eureka: false #不注册到Eureka 因为自己就是server
    fetch-registry: false #自己不从Eureka服务获取注册信息 因为自己就是server
    service-url:
      defaultZone: http://localhost:8671/eureka #配置Eureaka的服务地址